{
 "title": "Summary",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  { "title": "Validator Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hex Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_desc",
     "select": [
      [
       { "params": [ "hex_address" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_desc",
     "select": [
      [
       { "params": [ "val_address" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Oasis Node Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_node_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No. of Peers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_num_peers",
     "select": [
      [
       { "params": [ "num_peers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Validator Block Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_current_block_height",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Worker Epoch",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_worker_epoch_number",
     "select": [
      [
       { "params": [ "epoch_number" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Height Difference",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_height_difference",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Epoch Difference",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_epoch_diff",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "System Metrics Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}