{
 "title": "Validator monitoring metrics",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Validator Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hex Address",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_desc",
     "select": [
      [
       { "params": [ "address" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Address",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_desc",
     "select": [
      [
       { "params": [ "public_key" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Oasis Node Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Validator Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_validator_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oasis Node Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_node_version",
     "query": "SELECT \"v\" FROM \"oasis_node_version\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "No. of Peers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_num_peers",
     "select": [
      [
       { "params": [ "num_peers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Validator Block Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_current_block_height",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_block_time_diff",
     "select": [
      [
       { "params": [ "time_diff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Missed In Last 48hrs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_total_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Epoch Number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_worker_epoch_number",
     "select": [
      [
       { "params": [ "epoch_number" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Missed Block Range",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_continuous_missed_blocks",
     "select": [
      [
       { "params": [ "range" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No of Proposed Blocks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oasis_consensus_proposed_blocks{job=\"oasis-node\",backend=\"tendermint\",instance=\"0.0.0.0:3001\"}"
    }
   ]
  },
  {
   "title": "Abci Db Size (MiB)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oasis_abci_db_size{instance=\"0.0.0.0:3001\",job=\"oasis-node\"}"
    }
   ]
  },
  { "title": "Validator Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Escrow",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_self_delegation_balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voting power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_voting_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Address Balance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "oasis_address_balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}